### ISSUE TITLE
Possible Bug: Device name not getting passed into App

### ISSUE THREAD

**Issue by billmurrin** [iadgov/WALKOFF#165]
### Possible BUG Report

I"m building a custom App using the tutorials and also referencing existing plugins. Things appear to be configured correctly, it loads without error, appears in the GUI, and I can configure the respective device in the web interface. 

However, when I try to run any action on the App, I see the following types of errors.
```
[2017-11-10 21:55:28,812]  core.appinstance::ERROR - Cannot create app instance. app: MYAPPNAME, device: . Error: KeyError: 'serveruri'

Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/path/WALKOFF/core/loadbalancer.py", line 277, in __init__
    self.execute_workflow_worker()
  File "/path/WALKOFF/core/loadbalancer.py", line 305, in execute_workflow_worker
    start_input=start_input)
  File "/path/WALKOFF/core/executionelements/workflow.py", line 118, in execute
    next(executor)
  File "/path/WALKOFF/core/executionelements/workflow.py", line 146, in __execute
    self._accumulator[step.name] = step.get_output().result
AttributeError: 'NoneType' object has no attribute 'result'
```
It appears that the device name is not getting passed into the App. Since there is no device name getting passed in, App is erroring out and self.device_fields does not get created for the object.

When I explicitly declare the device name inside of my App, it works as intended.

FYI, I cloned from master. I couldn't find an existing issue so I figured I would post this.

Running in a VM using python 2.7.12

**Comment by JustinTervala** [comment]
Just released version 0.4.2 which should fix this issue.
